### ISSUE TITLE
Can't use github.com/lib/pq utilities

### ISSUE THREAD

**Issue by fiatjaf** [galeone/igor#4]
I'm trying to have a `pq.NullTime` in one of my models (any null-type will present the same problem), but importing `github.com/lib/pq` will cause a `panic: sql: Register called twice for driver postgres` due to the double import of that package -- one from my `GOPATH`, the other from the `vendor/` directory here.

Trying to import `github.com/galeone/igor/vendor/github.com/lib/pq` instead fails with `use of vendored package not allowed`.

This seems like a dead-end for me.
Perhaps it would be a good idea to stop vendoring `github.com/lib/pq` in this package?

**Comment by galeone** [comment]
I think you're right. In my tests, I always used nullable types from the `sql` package, but never from the `pq` . For this reason I didn't notice this issue.

Thank you for reporting this problem. I think I'm going to remove the vendor folder, I can't find out another possible solution to that.
